// Code generated by protoc-gen-go.
// source: server/node/gnode.proto
// DO NOT EDIT!

/*
Package node is a generated protocol buffer package.

It is generated from these files:
	server/node/gnode.proto

It has these top-level messages:
	AntMes
	AntRet
	HealthRequest
	PingRet
	AskConnectionRequest
	EmptyRet
*/
package node

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AntMes struct {
	Id           string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Origin       string   `protobuf:"bytes,2,opt,name=origin" json:"origin,omitempty"`
	FromClient   string   `protobuf:"bytes,3,opt,name=from_client,json=fromClient" json:"from_client,omitempty"`
	Target       string   `protobuf:"bytes,4,opt,name=target" json:"target,omitempty"`
	IsAnswer     bool     `protobuf:"varint,5,opt,name=isAnswer" json:"isAnswer,omitempty"`
	ReturnAnswer bool     `protobuf:"varint,6,opt,name=return_answer,json=returnAnswer" json:"return_answer,omitempty"`
	IsPathWriter bool     `protobuf:"varint,7,opt,name=is_path_writer,json=isPathWriter" json:"is_path_writer,omitempty"`
	OriginId     string   `protobuf:"bytes,8,opt,name=origin_id,json=originId" json:"origin_id,omitempty"`
	Path         []string `protobuf:"bytes,9,rep,name=path" json:"path,omitempty"`
	PathIndex    int32    `protobuf:"varint,10,opt,name=path_index,json=pathIndex" json:"path_index,omitempty"`
	Function     string   `protobuf:"bytes,11,opt,name=function" json:"function,omitempty"`
	Args         []string `protobuf:"bytes,12,rep,name=args" json:"args,omitempty"`
	TransferId   string   `protobuf:"bytes,13,opt,name=transfer_id,json=transferId" json:"transfer_id,omitempty"`
	Order        int64    `protobuf:"varint,14,opt,name=order" json:"order,omitempty"`
	NbBlockTotal int64    `protobuf:"varint,15,opt,name=nb_block_total,json=nbBlockTotal" json:"nb_block_total,omitempty"`
	NbBlock      int64    `protobuf:"varint,16,opt,name=nb_block,json=nbBlock" json:"nb_block,omitempty"`
	Size         int64    `protobuf:"varint,17,opt,name=size" json:"size,omitempty"`
	TargetedPath string   `protobuf:"bytes,18,opt,name=targeted_path,json=targetedPath" json:"targeted_path,omitempty"`
	NoBlocking   bool     `protobuf:"varint,19,opt,name=no_blocking,json=noBlocking" json:"no_blocking,omitempty"`
	Debug        bool     `protobuf:"varint,20,opt,name=debug" json:"debug,omitempty"`
	AnswerWait   bool     `protobuf:"varint,21,opt,name=answer_wait,json=answerWait" json:"answer_wait,omitempty"`
	ErrorMes     string   `protobuf:"bytes,22,opt,name=errorMes" json:"errorMes,omitempty"`
	NbThread     int32    `protobuf:"varint,23,opt,name=nb_thread,json=nbThread" json:"nb_thread,omitempty"`
	Thread       int32    `protobuf:"varint,24,opt,name=thread" json:"thread,omitempty"`
	Duplicate    int32    `protobuf:"varint,25,opt,name=duplicate" json:"duplicate,omitempty"`
	Version      int32    `protobuf:"varint,26,opt,name=version" json:"version,omitempty"`
	Eof          bool     `protobuf:"varint,27,opt,name=eof" json:"eof,omitempty"`
	UserName     string   `protobuf:"bytes,29,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	UserToken    string   `protobuf:"bytes,30,opt,name=user_token,json=userToken" json:"user_token,omitempty"`
	Nodes        []string `protobuf:"bytes,31,rep,name=nodes" json:"nodes,omitempty"`
	Data         []byte   `protobuf:"bytes,32,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *AntMes) Reset()                    { *m = AntMes{} }
func (m *AntMes) String() string            { return proto.CompactTextString(m) }
func (*AntMes) ProtoMessage()               {}
func (*AntMes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AntMes) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AntMes) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *AntMes) GetFromClient() string {
	if m != nil {
		return m.FromClient
	}
	return ""
}

func (m *AntMes) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *AntMes) GetIsAnswer() bool {
	if m != nil {
		return m.IsAnswer
	}
	return false
}

func (m *AntMes) GetReturnAnswer() bool {
	if m != nil {
		return m.ReturnAnswer
	}
	return false
}

func (m *AntMes) GetIsPathWriter() bool {
	if m != nil {
		return m.IsPathWriter
	}
	return false
}

func (m *AntMes) GetOriginId() string {
	if m != nil {
		return m.OriginId
	}
	return ""
}

func (m *AntMes) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *AntMes) GetPathIndex() int32 {
	if m != nil {
		return m.PathIndex
	}
	return 0
}

func (m *AntMes) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

func (m *AntMes) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *AntMes) GetTransferId() string {
	if m != nil {
		return m.TransferId
	}
	return ""
}

func (m *AntMes) GetOrder() int64 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *AntMes) GetNbBlockTotal() int64 {
	if m != nil {
		return m.NbBlockTotal
	}
	return 0
}

func (m *AntMes) GetNbBlock() int64 {
	if m != nil {
		return m.NbBlock
	}
	return 0
}

func (m *AntMes) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *AntMes) GetTargetedPath() string {
	if m != nil {
		return m.TargetedPath
	}
	return ""
}

func (m *AntMes) GetNoBlocking() bool {
	if m != nil {
		return m.NoBlocking
	}
	return false
}

func (m *AntMes) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

func (m *AntMes) GetAnswerWait() bool {
	if m != nil {
		return m.AnswerWait
	}
	return false
}

func (m *AntMes) GetErrorMes() string {
	if m != nil {
		return m.ErrorMes
	}
	return ""
}

func (m *AntMes) GetNbThread() int32 {
	if m != nil {
		return m.NbThread
	}
	return 0
}

func (m *AntMes) GetThread() int32 {
	if m != nil {
		return m.Thread
	}
	return 0
}

func (m *AntMes) GetDuplicate() int32 {
	if m != nil {
		return m.Duplicate
	}
	return 0
}

func (m *AntMes) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *AntMes) GetEof() bool {
	if m != nil {
		return m.Eof
	}
	return false
}

func (m *AntMes) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *AntMes) GetUserToken() string {
	if m != nil {
		return m.UserToken
	}
	return ""
}

func (m *AntMes) GetNodes() []string {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *AntMes) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AntRet struct {
	Ack bool   `protobuf:"varint,1,opt,name=ack" json:"ack,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *AntRet) Reset()                    { *m = AntRet{} }
func (m *AntRet) String() string            { return proto.CompactTextString(m) }
func (*AntRet) ProtoMessage()               {}
func (*AntRet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AntRet) GetAck() bool {
	if m != nil {
		return m.Ack
	}
	return false
}

func (m *AntRet) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type HealthRequest struct {
}

func (m *HealthRequest) Reset()                    { *m = HealthRequest{} }
func (m *HealthRequest) String() string            { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()               {}
func (*HealthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type PingRet struct {
	Host         string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	NbNode       int32  `protobuf:"varint,3,opt,name=nb_node,json=nbNode" json:"nb_node,omitempty"`
	NbDuplicate  int32  `protobuf:"varint,4,opt,name=nb_duplicate,json=nbDuplicate" json:"nb_duplicate,omitempty"`
	ClientNumber int32  `protobuf:"varint,5,opt,name=client_number,json=clientNumber" json:"client_number,omitempty"`
}

func (m *PingRet) Reset()                    { *m = PingRet{} }
func (m *PingRet) String() string            { return proto.CompactTextString(m) }
func (*PingRet) ProtoMessage()               {}
func (*PingRet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PingRet) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *PingRet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PingRet) GetNbNode() int32 {
	if m != nil {
		return m.NbNode
	}
	return 0
}

func (m *PingRet) GetNbDuplicate() int32 {
	if m != nil {
		return m.NbDuplicate
	}
	return 0
}

func (m *PingRet) GetClientNumber() int32 {
	if m != nil {
		return m.ClientNumber
	}
	return 0
}

type AskConnectionRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Host string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	Ip   string `protobuf:"bytes,3,opt,name=ip" json:"ip,omitempty"`
}

func (m *AskConnectionRequest) Reset()                    { *m = AskConnectionRequest{} }
func (m *AskConnectionRequest) String() string            { return proto.CompactTextString(m) }
func (*AskConnectionRequest) ProtoMessage()               {}
func (*AskConnectionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AskConnectionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AskConnectionRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *AskConnectionRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type EmptyRet struct {
}

func (m *EmptyRet) Reset()                    { *m = EmptyRet{} }
func (m *EmptyRet) String() string            { return proto.CompactTextString(m) }
func (*EmptyRet) ProtoMessage()               {}
func (*EmptyRet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*AntMes)(nil), "node.AntMes")
	proto.RegisterType((*AntRet)(nil), "node.AntRet")
	proto.RegisterType((*HealthRequest)(nil), "node.HealthRequest")
	proto.RegisterType((*PingRet)(nil), "node.PingRet")
	proto.RegisterType((*AskConnectionRequest)(nil), "node.AskConnectionRequest")
	proto.RegisterType((*EmptyRet)(nil), "node.EmptyRet")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GNodeService service

type GNodeServiceClient interface {
	ExecuteFunction(ctx context.Context, in *AntMes, opts ...grpc.CallOption) (*AntRet, error)
	CheckReceiver(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*AntRet, error)
	GetClientStream(ctx context.Context, opts ...grpc.CallOption) (GNodeService_GetClientStreamClient, error)
	AskConnection(ctx context.Context, in *AskConnectionRequest, opts ...grpc.CallOption) (*PingRet, error)
	Ping(ctx context.Context, in *AntMes, opts ...grpc.CallOption) (*PingRet, error)
	Healthcheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*AntRet, error)
}

type gNodeServiceClient struct {
	cc *grpc.ClientConn
}

func NewGNodeServiceClient(cc *grpc.ClientConn) GNodeServiceClient {
	return &gNodeServiceClient{cc}
}

func (c *gNodeServiceClient) ExecuteFunction(ctx context.Context, in *AntMes, opts ...grpc.CallOption) (*AntRet, error) {
	out := new(AntRet)
	err := grpc.Invoke(ctx, "/node.GNodeService/ExecuteFunction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gNodeServiceClient) CheckReceiver(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*AntRet, error) {
	out := new(AntRet)
	err := grpc.Invoke(ctx, "/node.GNodeService/CheckReceiver", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gNodeServiceClient) GetClientStream(ctx context.Context, opts ...grpc.CallOption) (GNodeService_GetClientStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GNodeService_serviceDesc.Streams[0], c.cc, "/node.GNodeService/GetClientStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &gNodeServiceGetClientStreamClient{stream}
	return x, nil
}

type GNodeService_GetClientStreamClient interface {
	Send(*AntMes) error
	Recv() (*AntMes, error)
	grpc.ClientStream
}

type gNodeServiceGetClientStreamClient struct {
	grpc.ClientStream
}

func (x *gNodeServiceGetClientStreamClient) Send(m *AntMes) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gNodeServiceGetClientStreamClient) Recv() (*AntMes, error) {
	m := new(AntMes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gNodeServiceClient) AskConnection(ctx context.Context, in *AskConnectionRequest, opts ...grpc.CallOption) (*PingRet, error) {
	out := new(PingRet)
	err := grpc.Invoke(ctx, "/node.GNodeService/AskConnection", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gNodeServiceClient) Ping(ctx context.Context, in *AntMes, opts ...grpc.CallOption) (*PingRet, error) {
	out := new(PingRet)
	err := grpc.Invoke(ctx, "/node.GNodeService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gNodeServiceClient) Healthcheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*AntRet, error) {
	out := new(AntRet)
	err := grpc.Invoke(ctx, "/node.GNodeService/Healthcheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GNodeService service

type GNodeServiceServer interface {
	ExecuteFunction(context.Context, *AntMes) (*AntRet, error)
	CheckReceiver(context.Context, *HealthRequest) (*AntRet, error)
	GetClientStream(GNodeService_GetClientStreamServer) error
	AskConnection(context.Context, *AskConnectionRequest) (*PingRet, error)
	Ping(context.Context, *AntMes) (*PingRet, error)
	Healthcheck(context.Context, *HealthRequest) (*AntRet, error)
}

func RegisterGNodeServiceServer(s *grpc.Server, srv GNodeServiceServer) {
	s.RegisterService(&_GNodeService_serviceDesc, srv)
}

func _GNodeService_ExecuteFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AntMes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNodeServiceServer).ExecuteFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.GNodeService/ExecuteFunction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNodeServiceServer).ExecuteFunction(ctx, req.(*AntMes))
	}
	return interceptor(ctx, in, info, handler)
}

func _GNodeService_CheckReceiver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNodeServiceServer).CheckReceiver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.GNodeService/CheckReceiver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNodeServiceServer).CheckReceiver(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GNodeService_GetClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GNodeServiceServer).GetClientStream(&gNodeServiceGetClientStreamServer{stream})
}

type GNodeService_GetClientStreamServer interface {
	Send(*AntMes) error
	Recv() (*AntMes, error)
	grpc.ServerStream
}

type gNodeServiceGetClientStreamServer struct {
	grpc.ServerStream
}

func (x *gNodeServiceGetClientStreamServer) Send(m *AntMes) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gNodeServiceGetClientStreamServer) Recv() (*AntMes, error) {
	m := new(AntMes)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GNodeService_AskConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNodeServiceServer).AskConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.GNodeService/AskConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNodeServiceServer).AskConnection(ctx, req.(*AskConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GNodeService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AntMes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNodeServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.GNodeService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNodeServiceServer).Ping(ctx, req.(*AntMes))
	}
	return interceptor(ctx, in, info, handler)
}

func _GNodeService_Healthcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GNodeServiceServer).Healthcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.GNodeService/Healthcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GNodeServiceServer).Healthcheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GNodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "node.GNodeService",
	HandlerType: (*GNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteFunction",
			Handler:    _GNodeService_ExecuteFunction_Handler,
		},
		{
			MethodName: "CheckReceiver",
			Handler:    _GNodeService_CheckReceiver_Handler,
		},
		{
			MethodName: "AskConnection",
			Handler:    _GNodeService_AskConnection_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _GNodeService_Ping_Handler,
		},
		{
			MethodName: "Healthcheck",
			Handler:    _GNodeService_Healthcheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetClientStream",
			Handler:       _GNodeService_GetClientStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "server/node/gnode.proto",
}

func init() { proto.RegisterFile("server/node/gnode.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 804 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0x1b, 0x37,
	0x10, 0xf6, 0xca, 0xfa, 0x1d, 0xaf, 0xec, 0x94, 0x71, 0x63, 0x46, 0x69, 0x1a, 0x75, 0xd3, 0x02,
	0x42, 0x81, 0x26, 0x85, 0x73, 0xed, 0xc5, 0x71, 0xd3, 0xd4, 0x07, 0x1b, 0xc1, 0xc6, 0x40, 0x8e,
	0x0b, 0xee, 0xee, 0x58, 0x22, 0x24, 0x91, 0x2a, 0x49, 0xd9, 0x69, 0x1f, 0xa3, 0x2f, 0xd4, 0xf7,
	0xe8, 0xd3, 0x14, 0x33, 0xdc, 0x75, 0x12, 0xb7, 0x05, 0x72, 0x11, 0x66, 0xbe, 0x6f, 0x86, 0xfb,
	0xf1, 0x1b, 0x0d, 0xe1, 0xc8, 0xa3, 0xbb, 0x46, 0xf7, 0xdc, 0xd8, 0x1a, 0x9f, 0xcf, 0xe9, 0xf7,
	0xd9, 0xc6, 0xd9, 0x60, 0x45, 0x97, 0xe2, 0xec, 0xef, 0x3e, 0xf4, 0x4f, 0x4c, 0x38, 0x47, 0x2f,
	0xf6, 0xa1, 0xa3, 0x6b, 0x99, 0x4c, 0x93, 0xd9, 0x28, 0xef, 0xe8, 0x5a, 0x3c, 0x80, 0xbe, 0x75,
	0x7a, 0xae, 0x8d, 0xec, 0x30, 0xd6, 0x64, 0xe2, 0x09, 0xec, 0x5d, 0x39, 0xbb, 0x2e, 0xaa, 0x95,
	0x46, 0x13, 0xe4, 0x2e, 0x93, 0x40, 0xd0, 0x29, 0x23, 0xd4, 0x18, 0x94, 0x9b, 0x63, 0x90, 0xdd,
	0xd8, 0x18, 0x33, 0x31, 0x81, 0xa1, 0xf6, 0x27, 0xc6, 0xdf, 0xa0, 0x93, 0xbd, 0x69, 0x32, 0x1b,
	0xe6, 0xb7, 0xb9, 0x78, 0x0a, 0x63, 0x87, 0x61, 0xeb, 0x4c, 0xa1, 0x62, 0x41, 0x9f, 0x0b, 0xd2,
	0x08, 0x36, 0x45, 0xdf, 0xc2, 0xbe, 0xf6, 0xc5, 0x46, 0x85, 0x45, 0x71, 0xe3, 0x74, 0x40, 0x27,
	0x07, 0xb1, 0x4a, 0xfb, 0x37, 0x2a, 0x2c, 0xde, 0x31, 0x26, 0x1e, 0xc1, 0x28, 0x2a, 0x2d, 0x74,
	0x2d, 0x87, 0xac, 0x60, 0x18, 0x81, 0xb3, 0x5a, 0x08, 0xe8, 0x52, 0xbf, 0x1c, 0x4d, 0x77, 0x67,
	0xa3, 0x9c, 0x63, 0xf1, 0x18, 0x80, 0xcf, 0xd4, 0xa6, 0xc6, 0xf7, 0x12, 0xa6, 0xc9, 0xac, 0x97,
	0x8f, 0x08, 0x39, 0x23, 0x80, 0x64, 0x5f, 0x6d, 0x4d, 0x15, 0xb4, 0x35, 0x72, 0x2f, 0x1e, 0xd7,
	0xe6, 0x74, 0x9c, 0x72, 0x73, 0x2f, 0xd3, 0x78, 0x1c, 0xc5, 0xe4, 0x4f, 0x70, 0xca, 0xf8, 0x2b,
	0x74, 0xa4, 0x60, 0x1c, 0xfd, 0x69, 0xa1, 0xb3, 0x5a, 0x1c, 0x42, 0xcf, 0xba, 0x1a, 0x9d, 0xdc,
	0x9f, 0x26, 0xb3, 0xdd, 0x3c, 0x26, 0x74, 0x39, 0x53, 0x16, 0xe5, 0xca, 0x56, 0xcb, 0x22, 0xd8,
	0xa0, 0x56, 0xf2, 0x80, 0xe9, 0xd4, 0x94, 0x2f, 0x09, 0xbc, 0x24, 0x4c, 0x3c, 0x84, 0x61, 0x5b,
	0x25, 0xef, 0x31, 0x3f, 0x68, 0x78, 0xd2, 0xe2, 0xf5, 0x1f, 0x28, 0xbf, 0x60, 0x98, 0x63, 0xb2,
	0x35, 0x9a, 0x8f, 0x35, 0xfb, 0x26, 0x05, 0xab, 0x49, 0x5b, 0x90, 0x6c, 0x23, 0xc1, 0xc6, 0xc6,
	0x33, 0xb5, 0x99, 0xcb, 0xfb, 0xec, 0x29, 0x18, 0xfb, 0xb2, 0x41, 0x48, 0x70, 0x8d, 0xe5, 0x76,
	0x2e, 0x0f, 0x99, 0x8a, 0x09, 0xb5, 0xc5, 0x59, 0x15, 0x37, 0x4a, 0x07, 0xf9, 0x65, 0x6c, 0x8b,
	0xd0, 0x3b, 0xa5, 0x79, 0xde, 0xe8, 0x9c, 0x75, 0xe7, 0xe8, 0xe5, 0x83, 0x68, 0x5c, 0x9b, 0xd3,
	0x90, 0x4c, 0x59, 0x84, 0x85, 0x43, 0x55, 0xcb, 0x23, 0xb6, 0x7c, 0x68, 0xca, 0x4b, 0xce, 0xf9,
	0x0f, 0x14, 0x19, 0xc9, 0x4c, 0x93, 0x89, 0xaf, 0x60, 0x54, 0x6f, 0x37, 0x2b, 0x5d, 0xa9, 0x80,
	0xf2, 0x61, 0x9c, 0xd3, 0x2d, 0x20, 0x24, 0x0c, 0xae, 0xd1, 0x79, 0x1a, 0xd3, 0x84, 0xb9, 0x36,
	0x15, 0xf7, 0x60, 0x17, 0xed, 0x95, 0x7c, 0xc4, 0x0a, 0x29, 0xa4, 0xcf, 0x6f, 0x3d, 0xba, 0xc2,
	0xa8, 0x35, 0xca, 0xc7, 0x51, 0x1b, 0x01, 0x17, 0x6a, 0x8d, 0xf4, 0x7f, 0x60, 0x32, 0xd8, 0x25,
	0x1a, 0xf9, 0x35, 0xb3, 0x5c, 0x7e, 0x49, 0x00, 0xb9, 0x41, 0xab, 0xe3, 0xe5, 0x13, 0x1e, 0x7a,
	0x4c, 0xc8, 0xfd, 0x5a, 0x05, 0x25, 0xa7, 0xd3, 0x64, 0x96, 0xe6, 0x1c, 0x67, 0xdf, 0xf3, 0x6e,
	0xe5, 0x18, 0x48, 0x81, 0xaa, 0x96, 0xbc, 0x5c, 0xc3, 0x9c, 0xc2, 0x66, 0xdb, 0x3a, 0xed, 0xb6,
	0x65, 0x07, 0x30, 0xfe, 0x15, 0xd5, 0x2a, 0x2c, 0x72, 0xfc, 0x6d, 0x8b, 0x3e, 0x64, 0x7f, 0x26,
	0x30, 0x78, 0xa3, 0xcd, 0x9c, 0xda, 0x05, 0x74, 0x17, 0xd6, 0x87, 0x66, 0x39, 0x39, 0x26, 0x8c,
	0xd5, 0xc7, 0x23, 0x38, 0x16, 0x47, 0x30, 0x30, 0x65, 0x41, 0x82, 0x78, 0x2d, 0x7b, 0x79, 0xdf,
	0x94, 0x17, 0xb6, 0x46, 0xf1, 0x0d, 0xa4, 0xa6, 0x2c, 0x3e, 0x98, 0xd7, 0x65, 0x76, 0xcf, 0x94,
	0x3f, 0xdf, 0xda, 0xf7, 0x14, 0xc6, 0x71, 0xa3, 0x0b, 0xb3, 0x5d, 0x97, 0xcd, 0x8a, 0xf6, 0xf2,
	0x34, 0x82, 0x17, 0x8c, 0x65, 0x17, 0x70, 0x78, 0xe2, 0x97, 0xa7, 0xd6, 0x18, 0xe4, 0x05, 0x68,
	0xc4, 0xde, 0x8a, 0x49, 0x3e, 0x12, 0xd3, 0x8a, 0xee, 0x7c, 0x24, 0x9a, 0x6e, 0xbd, 0x69, 0x9e,
	0x8c, 0x8e, 0xde, 0x64, 0x00, 0xc3, 0x57, 0xeb, 0x4d, 0xf8, 0x3d, 0xc7, 0x70, 0xfc, 0x57, 0x07,
	0xd2, 0xd7, 0xa4, 0xf6, 0x2d, 0xba, 0x6b, 0x5d, 0xa1, 0xf8, 0x01, 0x0e, 0x5e, 0xbd, 0xc7, 0x6a,
	0x1b, 0xf0, 0x97, 0x76, 0xdf, 0xd2, 0x67, 0xfc, 0x82, 0xc5, 0x17, 0x6b, 0xf2, 0x21, 0x23, 0x93,
	0x8e, 0x61, 0x7c, 0xba, 0xc0, 0x6a, 0x99, 0x63, 0x85, 0xfa, 0x1a, 0x9d, 0xb8, 0x1f, 0xe9, 0x4f,
	0x6c, 0xbd, 0xd3, 0xf3, 0x02, 0x0e, 0x5e, 0x63, 0x88, 0xef, 0xd6, 0xdb, 0xe0, 0x50, 0xad, 0xff,
	0xf7, 0x13, 0xe7, 0xe8, 0xb3, 0x9d, 0x59, 0xf2, 0x63, 0x22, 0x7e, 0x82, 0xf1, 0x27, 0x26, 0x88,
	0x49, 0x53, 0xf4, 0x1f, 0xce, 0x4c, 0xc6, 0x91, 0x6b, 0x26, 0x99, 0xed, 0x88, 0xef, 0xa0, 0x4b,
	0xc9, 0x9d, 0xef, 0xfc, 0xab, 0xec, 0x18, 0xf6, 0xa2, 0xf0, 0x8a, 0xee, 0xf4, 0x19, 0x77, 0xc9,
	0x76, 0xca, 0x3e, 0xbf, 0xec, 0x2f, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x33, 0xca, 0x01, 0x56,
	0xf4, 0x05, 0x00, 0x00,
}
